### ISSUE TITLE
Default to 1 Pane

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-web#15]
On initial load the site should default to 2 panes instead of 3.

**Comment by codemis** [comment]
Currently, the default is one window Version ULB Genesis 1 v1.  If 2 panes, what versions do you want open?

**Comment by jag3773** [comment]
OK, I think that's fine then.

**Comment by jag3773** [comment]
I'm reopening this because I've tried opening the site on 4 different browsers and they all come up with 3 panes open.  What's going on?

**Comment by jag3773** [comment]
Let's double check that we are set to 1 pane and defaulting to the ULB.
