### ISSUE TITLE
Integrate uW Catalog

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-web#2]
The catalog at https://api.unfoldingword.org/uw/txt/2/catalog.json gives a complete list of the Scripture (and other resources) that we have published.  We need this app to be able to read from the catalog and present the biblical resources available in it.
## UPDATE

The publish process for the api needs to be updated so that html is generated for use in uw-web. [USFM-tools](https://github.com/unfoldingWord-dev/USFM-Tools) is able to convert the usfm files to html. The code for the api update can be found in [tools](https://github.com/unfoldingWord-dev/tools).

The generated html should be placed in a new location in the api that is accessible to and structured for uw-web.

**Comment by codemis** [comment]
Fixed this issue.
