### ISSUE TITLE
Only regenerate uW Texts

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-web#20]
Can we either change `generate.js -a` or add a new flag that only regenerates the uW Bibles?  Generally the other Bible's will not change very often so it doesn't make sense to rebuild those every time, but we will want to rebuild the unfoldingWord texts each time.

**Comment by codemis** [comment]
Created a [pull request](https://github.com/unfoldingWord-dev/uw-web/pull/26) to merge into develop.
