### ISSUE TITLE
Incorporate into unfoldingword.org

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-web#3]
We need to figure out a good way to incorporate this into unfoldingword.org.  Possibly we can run this on a sub domain, perhaps bible.unfoldingword.org?  Also, does this _require_ a server side PHP component?  Can we run it all in the browser, say off of AWS S3?
## UPDATE

uw-web can be ran out of a directory or subdomain. Everything is browser side so no backend support like php or python is nessesary.

**Comment by alerque** [comment]
No this does not require server side PHP, and yes you can run it all in a browser (and server it off of S3). It was designed to be able to drop static files on a USB stick and run off of that with no Internet involved, so serving it up over the web is a pretty  basic operation with no special requirements.

Doing the initial import of Bible content from standard markup formats to BB3's static pre-generated HTML markup format is a one time operation done using mostly NodeJS and can be done anywhere and then push the static generated out to wherever you serve it from.

**Comment by da1nerd** [comment]
We have a mostly completed tool (somewhere) that converts the data in our api to static html files that can be loaded into BB3.

The plan thus far is to add a step to our publishing process that performs this html generation.
