### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/uw-web#31]
I got an email from a user who said this, talking about a language page in unfoldingword.org "It was not easy for me to find the link, look at file hosting websites  they have at list 2-3 links "download now" that so visual. You guys set pdf icon that shown only if you click on dropdown.  I think that click is extra click that not needed." 

Personally, I don't think we need to explain OBS + Bible translation + translation resources on each language page. It clutters the page. We could have a link in each page to where this is explained, but I don't think it needs to be on every page. I think a simple design with the titles of the resources would be great + each resource with a "View Online" and "Download" button that popped out into a menu of options when clicked, I think it would de-clutter the page significantly and still make everything easy to find. (Maybe have a "Multimedia" button too for audio and video.)

I also find the unfoldingword.org/stories difficult to find content. It would be a lot easier to find content if all the languages with published content rose to the top and the languages in process came in underneath.

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord/unfoldingWord.github.io#183
