### ISSUE TITLE
Add Print Function

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-web#4]
Initially, we need a simple print to PDF function where at least the range of text and resource to be printed can be selected.  This will eventually become a full blown in browser print preview where items can be rearranged and the preview dynamically updated.
## UPDATE

The rendering of the previews will be handled on the server. The print/preview commands will need to communicate with [uw-publisher](https://github.com/unfoldingWord-dev/uw-publisher).

**Comment by alerque** [comment]
I would suggest that this feature is not good fit for doing inside of BB3. I already looked at it rather extensively (if you look at the contributors list you'll see I have spent some quality time with the code you forked from already) and the way BB3 is architected to run inside the browser using statically generated source files is fantastic for some purposes and not at all suited to others. Generating PDFs on the fly (or basically any sane print view) is not one of them. It's not impossible but I would suggest it's not a road you want to go down. Yet.

Instead I suggest this needs to be designed as a stand alone API call where the PDF is generated on the server. It would have it's own copy of the source data in a format that is structurally meaningful (OSIS perhaps) to a typesetter (as opposed to BB3's backend data which is formatted to be meaningful markup on the web) and accept verse ranges and layout parameters as arguments and would return the completed PDF.

I already have been working on something similar for a site I run and would be happy to compare notes with anybody that's actually going to work on this and maybe even work together on the common bits. I'm going to be using the [SILE typesetting engine](https://github.com/simoncozens/sile/) (which as you can see I've been spending some quality time with too) for my own project, but another angle you could take on this would be to use the Sword project's LaTeX output format.

Any way you go for building the on demand API, you can still build yourself a front-end plugin to surface the function to end users in BB3. I just think trying to build the actual Bible text processing and typesetting logic into BB3 would be picking up this snake an the wrong end!

**Comment by da1nerd** [comment]
@alerque great thinking. That was the pattern we had decided on at Orlando C4TK. This api has been half implemented. The front end will just be configured to request a range of passages in a specific format and the server will generate the output from the raw source.

The tricky part will be in presenting a preview of the output. I suppose we could do so by automatically requesting a rendering of the first page of the output and showing that to the user.

**Comment by da1nerd** [comment]
The last update to this included the addition of a print dialog in which you could choose what range of passages to print. This was very rudimentary and needs a lot of TLC.

@alerque I have not spent a ton of time in the code. Is there any support for modules/extensions?

**Comment by alerque** [comment]
@neutrinog Not officially no. And since it it's only setup to interact with itself it is a bit of a spaghetti pile as far as what talks to what when. But for all that it does have some semblance of a modular approach to it's own functionality so it at least you'd be able to keep the code for this feature all together in a couple of chunks and just extend a few feelers so you get called at the right places and can inject the interface pieces you need.
