### ISSUE TITLE
Finish updating HTML rendering functionality

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord-dev/uw-web#6]
The html rendering is handled  by https://github.com/unfoldingWord-dev/USFM-Tools.
The rendering should be mostly finished, but it needs to be checked for bugs.

**Comment by codemis** [comment]
@neutrinog Question? Is that render designed to work with this repo's HTML conversion of the uW texts?  I ask because the current rendering is done in NodeJS.

**Comment by da1nerd** [comment]
I seem to recall that was the plan yes. The render should just take raw html.
